/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <inttypes.h>

#define PRIMENUMBERSCOUNT 13000

int * loadPrimeNumbers();
int countDivisors(int64_t number,int * primeNumbers);


int main()
{
    int * primeNumbers = loadPrimeNumbers();
    int64_t number = 1;
    int64_t increment = 2;
    int count = 0;
    while((count = countDivisors(number,primeNumbers))<=500)
        {
            number+=increment++;
        }
    printf("result: %"PRId64,number);
    return 0;
}

int* loadPrimeNumbers()
{
    bool primeBits[140000];
    int i;
    int j;
    for(i = 2;i<140000;i++)
        {
           for(j = 2*i;j<140000;j+=i)
            {
                primeBits[j]=1;
            }
        }
    static int primeNumbers[PRIMENUMBERSCOUNT];
    int counter = 0;
    for(i = 2;i<140000&&counter<PRIMENUMBERSCOUNT;i++)
        {
            if(primeBits[i]==0)
                {
                    primeNumbers[counter++] = i;
                }
        }
    return primeNumbers;
}
int countDivisors(int64_t number, int * primeNumbers)
{
    int powerOfFactors[PRIMENUMBERSCOUNT];
    int i;
    for(i = 0; i<PRIMENUMBERSCOUNT;i++)
        {
            powerOfFactors[i] = 0;
        }
    while(number!=1)
        {

            for(i = 0; i<PRIMENUMBERSCOUNT;i++)
                {
                    if(number%*(primeNumbers+i)==0)
                        {
                            powerOfFactors[*(primeNumbers+i)]++;
                            number/=*(primeNumbers+i);
                            break;
                        }
                }
        }
    int countPower = 1;
    for(i = 0;i<PRIMENUMBERSCOUNT;i++)
        {
            if(powerOfFactors[i]!=0)
                {
                    countPower*= powerOfFactors[i]+1;
                }
        }
    return countPower;
}
